# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170824_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='post_likes', to='music.Profile'),
        ),
    ]
