# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170824_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='songref',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
