# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_userlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
