# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_remove_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
