# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20170828_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedetail',
            old_name='song',
            new_name='song_id',
        ),
    ]
