# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20170828_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedetail',
            old_name='profile',
            new_name='profile_id',
        ),
    ]
