# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20170829_0001'),
        ('music', '0005_auto_20170425_0954'),
    ]

    operations = [
    ]
